jobs:
  main:
    requires: [~commit, ~pr]
    image: node:18
    secrets: [PROD_SECRET]
    steps:
      - probe_in_pr: echo "PRJOB PROD_SECRET=[$PROD_SECRET]"
  deploy:
    requires: [main]
    image: node:18
    secrets: [PROD_SECRET]
    steps:
      - probe_secret: echo "PROBE PROD_SECRET=[$PROD_SECRET]"
